[background]
mode = "file"
path = "/home/ns/Downloads/colin-watts-M1ObxvsWVhY-unsplash.jpg"
color = "#202833"
blur_radius = 10
dim_strength = 54
tint = "rgba(255, 255, 255, 0.1)"
tint_opacity = 0

[visuals.clock]
format = "12h"
meridiem_size = 3
meridiem_offset_x = 6
meridiem_offset_y = 7
font_family = "Raleway"
font_weight = 600
font_style = "italic"
color = "#ffffff"
opacity = 40
size = 14
gap = 20

[visuals.date]
enabled = false
font_family = "Google Sans Flex"
font_weight = 400
color = "#C8D8F2"
opacity = 72

[visuals.input]
alignment = "bottom-center"
horizontal_padding = 0
vertical_padding = 0
offset_x = 0
offset_y = 0
background_color = "#FFFFFF"
background_opacity = 8
border_color = "#FFFFFF"
border_width = 0
border_opacity = 0
width = 310
height = 54
radius = 50
mask_color = "#ffffff"
font_family = "Google Sans Flex"
font_weight = 400
font_size = 2

[visuals.placeholder]
color = "#ffffff"
opacity = 60

[visuals.avatar]
enabled = false

[visuals.username]
enabled = false

[visuals.keyboard]
background_size = 46
background_color = "rgba(255, 255, 255, 0.05)"
color = "#ffffff"
opacity = 68
size = 2
top_offset = -44
right_offset = 8

[visuals.battery]
enabled = true
background_color = "rgba(234, 242, 255, 0.08)"
color = "#F8FBFF"

[visuals.weather]
enabled = false
alignment = "right"
horizontal_padding = 56
temperature_color = "#F8FBFF"
location_color = "#C8D8F2"

[visuals.now_playing]
enabled = false
title_color = "#F8FBFF"
artist_color = "#C8D8F2"
opacity = 78
artwork_radius = 12
