[package]
name = "veila-daemon"
description = "Lock orchestration daemon and control library for Veila"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
veila-common = { path = "../common" }
zeroize = { workspace = true }
veila-renderer = { path = "../renderer" }
veila-ui = { path = "../ui" }
anyhow = { workspace = true }
futures-util = { workspace = true }
nix = { workspace = true }
nonstick = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smithay-client-toolkit = { workspace = true }
tokio = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
ureq = { workspace = true }
zbus = { workspace = true }
